services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_DATABASE: health
      MYSQL_ROOT_PASSWORD: Ashok@123
    ports:
      - "3308:3306"   # external:internal
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ecommerce-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/healthrecord
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Ashok@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8081:8080"   # âœ… correct mapping
    networks:
      - ecommerce-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge
